### ISSUE TITLE
missing code?

### ISSUE THREAD

**Issue by totalspectrum** [ironsheep/p2-LED-Matrix-Driver#1]
I wanted to try compiling your code with flexspin, but I don't see any .spin2 files (or indeed anything that looks like code) in the repository. Is something missing, or have I overlooked something?

Thanks, Eric

**Comment by ironsheep** [comment]
Eric, see the develop/ branch.  I'm still working toward the initial release.  There's a good test for you there.  The top files are isp_hub75_demo*.spin2

**Comment by ironsheep** [comment]
Eric found the code... (on develop branch at the time)
